-- Agency Team V2 — multi-user fleet management with server-side roles.
-- Roles: admin, reservations, operations, finance. Owner always has full access.

create schema if not exists private;
revoke all on schema private from public;

do $$ begin create type public.agency_member_role as enum ('admin','reservations','operations','finance'); exception when duplicate_object then null; end $$;
do $$ begin create type public.agency_member_status as enum ('active','suspended'); exception when duplicate_object then null; end $$;
do $$ begin create type public.agency_invite_status as enum ('pending','accepted','revoked','expired'); exception when duplicate_object then null; end $$;

create table if not exists public.agency_accounts(id uuid primary key default gen_random_uuid(),owner_id uuid not null unique references public.profiles(id) on delete cascade,name text,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.agency_members(id uuid primary key default gen_random_uuid(),agency_id uuid not null references public.agency_accounts(id) on delete cascade,user_id uuid not null references public.profiles(id) on delete cascade,role public.agency_member_role not null,status public.agency_member_status not null default 'active',joined_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(agency_id,user_id));
create table if not exists public.agency_invites(id uuid primary key default gen_random_uuid(),agency_id uuid not null references public.agency_accounts(id) on delete cascade,token uuid not null unique default gen_random_uuid(),email text,role public.agency_member_role not null,status public.agency_invite_status not null default 'pending',created_by uuid not null references public.profiles(id),expires_at timestamptz not null default(now()+interval '7 days'),accepted_by uuid references public.profiles(id),accepted_at timestamptz,created_at timestamptz not null default now());
create table if not exists public.agency_audit_logs(id bigint generated always as identity primary key,agency_id uuid not null references public.agency_accounts(id) on delete cascade,actor_id uuid references public.profiles(id),action text not null,entity_type text,entity_id text,metadata jsonb not null default '{}'::jsonb,created_at timestamptz not null default now());
create index if not exists agency_members_user_idx on public.agency_members(user_id,status);
create index if not exists agency_invites_agency_idx on public.agency_invites(agency_id,created_at desc);
create index if not exists agency_logs_agency_idx on public.agency_audit_logs(agency_id,created_at desc);

alter table public.agency_accounts enable row level security; alter table public.agency_members enable row level security; alter table public.agency_invites enable row level security; alter table public.agency_audit_logs enable row level security;
grant select on public.agency_accounts,public.agency_members,public.agency_invites,public.agency_audit_logs to authenticated;

create or replace function private.agency_role_for_owner(p_owner uuid,p_user uuid default auth.uid()) returns text language sql stable security definer set search_path=public,private as $$ select case when p_user=p_owner then 'owner' else (select am.role::text from public.agency_accounts aa join public.agency_members am on am.agency_id=aa.id where aa.owner_id=p_owner and am.user_id=p_user and am.status='active' limit 1) end $$;
create or replace function private.agency_can(p_owner uuid,p_permission text,p_user uuid default auth.uid()) returns boolean language plpgsql stable security definer set search_path=public,private as $$ declare r text; begin r:=private.agency_role_for_owner(p_owner,p_user); if r in ('owner','admin') then return true; end if; if p_permission='view' and r in ('reservations','operations','finance') then return true; end if; if p_permission='reservations' and r='reservations' then return true; end if; if p_permission='operations' and r='operations' then return true; end if; if p_permission='finance' and r='finance' then return true; end if; return false; end $$;
create or replace function private.agency_user_in_agency(p_agency uuid,p_user uuid default auth.uid()) returns boolean language sql stable security definer set search_path=public,private as $$ select exists(select 1 from public.agency_accounts a where a.id=p_agency and a.owner_id=p_user) or exists(select 1 from public.agency_members m where m.agency_id=p_agency and m.user_id=p_user and m.status='active') $$;
create or replace function private.log_agency(p_agency uuid,p_action text,p_entity_type text default null,p_entity_id text default null,p_metadata jsonb default '{}'::jsonb) returns void language sql security definer set search_path=public,private as $$ insert into public.agency_audit_logs(agency_id,actor_id,action,entity_type,entity_id,metadata) values(p_agency,auth.uid(),p_action,p_entity_type,p_entity_id,coalesce(p_metadata,'{}'::jsonb)) $$;
revoke all on function private.agency_role_for_owner(uuid,uuid),private.agency_can(uuid,text,uuid),private.agency_user_in_agency(uuid,uuid),private.log_agency(uuid,text,text,text,jsonb) from public;
grant execute on function private.agency_role_for_owner(uuid,uuid),private.agency_can(uuid,text,uuid),private.agency_user_in_agency(uuid,uuid) to authenticated;

drop policy if exists "agency account visible to team" on public.agency_accounts; create policy "agency account visible to team" on public.agency_accounts for select to authenticated using(owner_id=auth.uid() or private.agency_user_in_agency(id,auth.uid()));
drop policy if exists "agency members visible to team" on public.agency_members; create policy "agency members visible to team" on public.agency_members for select to authenticated using(private.agency_user_in_agency(agency_id,auth.uid()));
drop policy if exists "agency invites visible to managers" on public.agency_invites; create policy "agency invites visible to managers" on public.agency_invites for select to authenticated using(exists(select 1 from public.agency_accounts a where a.id=agency_id and private.agency_role_for_owner(a.owner_id,auth.uid()) in ('owner','admin')));
drop policy if exists "agency logs visible to managers" on public.agency_audit_logs; create policy "agency logs visible to managers" on public.agency_audit_logs for select to authenticated using(exists(select 1 from public.agency_accounts a where a.id=agency_id and private.agency_role_for_owner(a.owner_id,auth.uid()) in ('owner','admin')));

create or replace function public.ensure_agency_account() returns uuid language plpgsql security definer set search_path=public,private as $$ declare u uuid:=auth.uid(); a uuid; begin if u is null then raise exception 'Not authenticated'; end if; if not exists(select 1 from public.boats where client_id=u) then raise exception 'Boat owner required'; end if; insert into public.agency_accounts(owner_id,name) values(u,'Mon agence') on conflict(owner_id) do nothing; select id into a from public.agency_accounts where owner_id=u; return a; end $$;
create or replace function public.agency_context() returns jsonb language plpgsql security definer set search_path=public,private as $$ declare u uuid:=auth.uid(); a public.agency_accounts%rowtype; m public.agency_members%rowtype; begin select * into a from public.agency_accounts where owner_id=u limit 1; if found then return jsonb_build_object('agency_id',a.id,'owner_id',a.owner_id,'role','owner','name',a.name); end if; select * into m from public.agency_members where user_id=u and status='active' order by joined_at limit 1; if not found then return '{}'::jsonb; end if; select * into a from public.agency_accounts where id=m.agency_id; return jsonb_build_object('agency_id',a.id,'owner_id',a.owner_id,'role',m.role::text,'name',a.name,'member_id',m.id); end $$;

create or replace function public.agency_create_invite(p_role public.agency_member_role,p_email text default null) returns jsonb language plpgsql security definer set search_path=public,private as $$ declare u uuid:=auth.uid(); a public.agency_accounts%rowtype; i public.agency_invites%rowtype; begin select * into a from public.agency_accounts where owner_id=u or id in(select agency_id from public.agency_members where user_id=u and status='active' and role='admin') order by(owner_id=u) desc limit 1; if not found then raise exception 'Agency admin required'; end if; insert into public.agency_invites(agency_id,email,role,created_by) values(a.id,nullif(lower(trim(p_email)),''),p_role,u) returning * into i; perform private.log_agency(a.id,'invite_created','invite',i.id::text,jsonb_build_object('role',p_role::text,'email',i.email)); return jsonb_build_object('id',i.id,'token',i.token,'role',i.role,'email',i.email,'expires_at',i.expires_at); end $$;

create or replace function public.agency_accept_invite(p_token uuid) returns jsonb language plpgsql security definer set search_path=public,private,auth as $$ declare u uuid:=auth.uid(); i public.agency_invites%rowtype; em text; m public.agency_members%rowtype; begin if u is null then raise exception 'Not authenticated'; end if; select * into i from public.agency_invites where token=p_token for update; if not found or i.status<>'pending' then raise exception 'Invitation invalid'; end if; if i.expires_at<now() then update public.agency_invites set status='expired' where id=i.id; raise exception 'Invitation expired'; end if; select lower(email) into em from auth.users where id=u; if i.email is not null and i.email<>em then raise exception 'Invitation reserved for another email'; end if; insert into public.agency_members(agency_id,user_id,role,status) values(i.agency_id,u,i.role,'active') on conflict(agency_id,user_id) do update set role=excluded.role,status='active',updated_at=now() returning * into m; update public.agency_invites set status='accepted',accepted_by=u,accepted_at=now() where id=i.id; perform private.log_agency(i.agency_id,'invite_accepted','member',m.id::text,jsonb_build_object('role',m.role::text)); return jsonb_build_object('agency_id',i.agency_id,'member_id',m.id,'role',m.role); end $$;

create or replace function public.agency_update_member(p_member uuid,p_role public.agency_member_role default null,p_status public.agency_member_status default null) returns jsonb language plpgsql security definer set search_path=public,private as $$ declare m public.agency_members%rowtype; a public.agency_accounts%rowtype; begin select * into m from public.agency_members where id=p_member for update; if not found then raise exception 'Member not found'; end if; select * into a from public.agency_accounts where id=m.agency_id; if private.agency_role_for_owner(a.owner_id,auth.uid()) not in ('owner','admin') then raise exception 'Agency admin required'; end if; update public.agency_members set role=coalesce(p_role,role),status=coalesce(p_status,status),updated_at=now() where id=p_member returning * into m; perform private.log_agency(a.id,'member_updated','member',m.id::text,jsonb_build_object('role',m.role::text,'status',m.status::text)); return jsonb_build_object('id',m.id,'role',m.role,'status',m.status); end $$;
create or replace function public.agency_revoke_invite(p_invite uuid) returns void language plpgsql security definer set search_path=public,private as $$ declare i public.agency_invites%rowtype; a public.agency_accounts%rowtype; begin select * into i from public.agency_invites where id=p_invite for update; if not found then raise exception 'Invite not found'; end if; select * into a from public.agency_accounts where id=i.agency_id; if private.agency_role_for_owner(a.owner_id,auth.uid()) not in ('owner','admin') then raise exception 'Agency admin required'; end if; update public.agency_invites set status='revoked' where id=i.id and status='pending'; perform private.log_agency(a.id,'invite_revoked','invite',i.id::text,'{}'::jsonb); end $$;

create or replace function public.agency_set_rental_status(p_request uuid,p_status text) returns void language plpgsql security definer set search_path=public,private as $$ declare r public.boat_rental_requests%rowtype; a public.agency_accounts%rowtype; begin select * into r from public.boat_rental_requests where id=p_request for update; if not found then raise exception 'Rental not found'; end if; if not private.agency_can(r.owner_id,'reservations',auth.uid()) then raise exception 'Reservation permission required'; end if; if r.status<>'pending' or r.payment_status<>'unpaid' or p_status not in('accepted','declined') then raise exception 'Invalid rental transition'; end if; update public.boat_rental_requests set status=p_status,updated_at=now() where id=p_request; select * into a from public.agency_accounts where owner_id=r.owner_id; if found then perform private.log_agency(a.id,'rental_'||p_status,'rental',r.id::text,jsonb_build_object('boat_id',r.boat_id)); end if; end $$;
create or replace function public.agency_create_block(p_boat uuid,p_starts timestamptz,p_ends timestamptz,p_type text,p_title text default null,p_notes text default null) returns uuid language plpgsql security definer set search_path=public,private as $$ declare b public.boats%rowtype; a public.agency_accounts%rowtype; bid uuid; begin select * into b from public.boats where id=p_boat; if not found then raise exception 'Boat not found'; end if; if not private.agency_can(b.client_id,'operations',auth.uid()) then raise exception 'Operations permission required'; end if; if p_ends<=p_starts or p_type not in('maintenance','private_use','unavailable') then raise exception 'Invalid block'; end if; insert into public.boat_availability_blocks(boat_id,owner_id,starts_at,ends_at,block_type,title,notes) values(p_boat,b.client_id,p_starts,p_ends,p_type,p_title,p_notes) returning id into bid; select * into a from public.agency_accounts where owner_id=b.client_id; if found then perform private.log_agency(a.id,'block_created','boat_block',bid::text,jsonb_build_object('boat_id',p_boat,'type',p_type)); end if; return bid; end $$;
create or replace function public.agency_delete_block(p_block uuid) returns void language plpgsql security definer set search_path=public,private as $$ declare b public.boat_availability_blocks%rowtype; a public.agency_accounts%rowtype; begin select * into b from public.boat_availability_blocks where id=p_block for update; if not found then raise exception 'Block not found'; end if; if not private.agency_can(b.owner_id,'operations',auth.uid()) then raise exception 'Operations permission required'; end if; delete from public.boat_availability_blocks where id=p_block; select * into a from public.agency_accounts where owner_id=b.owner_id; if found then perform private.log_agency(a.id,'block_deleted','boat_block',p_block::text,jsonb_build_object('boat_id',b.boat_id)); end if; end $$;

-- Dashboard snapshot is security-definer and deliberately filters finance/customer data by role.
-- Keep direct team SELECT policies off boat_rental_requests and boat_availability_blocks.
drop policy if exists "agency team reads rentals" on public.boat_rental_requests;
drop policy if exists "agency team reads blocks" on public.boat_availability_blocks;

revoke all on function public.ensure_agency_account(),public.agency_context(),public.agency_create_invite(public.agency_member_role,text),public.agency_accept_invite(uuid),public.agency_update_member(uuid,public.agency_member_role,public.agency_member_status),public.agency_revoke_invite(uuid),public.agency_set_rental_status(uuid,text),public.agency_create_block(uuid,timestamptz,timestamptz,text,text,text),public.agency_delete_block(uuid) from public,anon;
grant execute on function public.ensure_agency_account(),public.agency_context(),public.agency_create_invite(public.agency_member_role,text),public.agency_accept_invite(uuid),public.agency_update_member(uuid,public.agency_member_role,public.agency_member_status),public.agency_revoke_invite(uuid),public.agency_set_rental_status(uuid,text),public.agency_create_block(uuid,timestamptz,timestamptz,text,text,text),public.agency_delete_block(uuid) to authenticated;
