create table if not exists public.bookings (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  user_id uuid not null references auth.users(id) on delete cascade,
  skipper_name text,
  port text,
  mission_date date,
  duration text,
  boat text,
  phone text,
  message text,
  status text not null default 'pending'
);

alter table public.bookings enable row level security;

create policy "Users can view own bookings"
on public.bookings for select
using (auth.uid() = user_id);

create policy "Users can create own bookings"
on public.bookings for insert
with check (auth.uid() = user_id);
